### PR TITLE
add shared before each

### PR DESCRIPTION
**Pull request by ylv-io**
# Description

No more!
image

## Type of change

- [x] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [ ] The diff is legible and has no extraneous changes
- [ ] Complex code has been commented, including external interfaces
- [ ] Tests are included for all code paths
- [x] The base branch is either `master`, or there's a description of how to merge

### CODE REVIEW

**Comment by nventuro** [comment]
@jubeira will like this

**Comment by EndymionJkb** [comment]
> @jubeira will like this

Me too: I was never comfortable with this voodoo where it still finds things somehow even when they're not imported anywhere. There might be more things like this

**Review by jubeira — APPROVED** [review]
Yes!

I realized this was wrong only a few months ago, and I was slowly adding it to the files that I was modifying for other purposes one at the time (it never affected the functionality of the tests apparently).
+1 to solve those red lines once and for all.

**Comment by EndymionJkb** [comment]
We just got used to all these little things over time.

We were boiled like frogs.

Thanks to the new frog for noticing the water temperature! :)

**Pull request merged**
