### PR TITLE
Deployment: Silo Linear Pool Factory

### PR DESCRIPTION
**Pull request by baileyspraggins**
# Deployment: SiloLinearPoolFactory

## Deployment tasks checklist:

- [x] Contract(s) deployed to all target networks / testnets
- [x] TX IDs are properly generated
- [x] Action IDs are generated after deployment (if applicable) 
- [x] Outputs for all target networks are generated, and linked in the task `readme`
- [x] Contracts are verified in every network 
- [x] Deployments `CHANGELOG` is updated
- [ ] There are no code changes of any kind

### Code changes (index.ts)
- Added the initialization of assetStorage and interestData with the mockSIlo
- Setting the total supply of the mockShareToken
- Fixed issues with calling .getPausedState() and verifying the mockSilo. I should have been using the mockSiloLinearPool for both.

### CODE REVIEW

**Review by EndymionJkb — COMMENTED** [review]
The task readme should have the output links added: 

\[Ethereum mainnet addresses](./output/mainnet.json)
\[Goerli testnet addresses](./output/goerli.json)

Also, I'd document the changes made to the "LIVE" part of the fork test.

Maybe we need to try deploying to the testnet as part of the deployment preparation, to make sure that part of the fork test works, at least for these complex cases.

Hopefully the new deployment repo will make this easier; you'll be able to run the fork tests in CI there, make PRs directly without having to fork, etc.

**Comment by baileyspraggins** [comment]
> 



> The task readme should have the output links added:
> 
> [Ethereum mainnet addresses](./output/mainnet.json) [Goerli testnet addresses](./output/goerli.json)
> 
> Also, I'd document the changes made to the "LIVE" part of the fork test.
> 
> Maybe we need to try deploying to the testnet as part of the deployment preparation, to make sure that part of the fork test works, at least for these complex cases.
> 
> Hopefully the new deployment repo will make this easier; you'll be able to run the fork tests in CI there, make PRs directly without having to fork, etc.

By "LIVE" part of the fork-tests are you referring to the deployment of the mocks? And I would say deploying to the testnet would be a helpful addition to the deployment preparation. 

>

**Comment by EndymionJkb** [comment]
> By "LIVE" part of the fork-tests are you referring to the deployment of the mocks?

Yes; ideally the fork test should be complete in the deployment prep stage, and not need to be modified later. This has happened a couple times already, with this one needing the most changes. Of course, I understand how this happens: especially when the issue is in the LIVE section, and only runs during the actual deployment.

It wouldn't hurt to do a live testnet deployment (when there is a LIVE section, as there is for factory deployments), just to make sure that part is going to work. That would avoid these issues. I'll update the Notion guidelines and add that. (You could even leave the generated files there and check them into the deployment PR later, so you don't need to do it twice.)

Other problems arise from not being able to run the fork test in CI *at all* until it's already merged: e.g., I've had to adjust some later because they were developed in the Orb repo and still had dependencies that I missed. The new deployments repo should address that.

**Review by EndymionJkb — COMMENTED** [review]
One last thing: just noticed you're adding the CHANGELOG entry to a previously released version: 3.2.0. It should be at the top, under Unreleased.

After that, this should be good-to-go.

**Comment by EndymionJkb** [comment]
Overtaken by events: new LinearPool factory released

**Pull request closed without merging**
