### PR TITLE
Remove warnings from linter

### PR DESCRIPTION
**Pull request by ylv-io**
# Description

image
Much better 😍

## Type of change

- [x] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [ ] The diff is legible and has no extraneous changes
- [ ] Complex code has been commented, including external interfaces
- [ ] Tests are included for all code paths
- [x] The base branch is either `master`, or there's a description of how to merge

### CODE REVIEW

**Review by EndymionJkb — COMMENTED** [review]
Glad to have you on the list!

I'm still getting those if I run at the package level though (e.g., standalone-utils) - even if I put the same line in the local package.json...

**Comment by ylv-io** [comment]
> Glad to have you on the list!
> 
> I'm still getting those if I run at the package level though (e.g., standalone-utils) - even if I put the same line in the local package.json...

This works @EndymionJkb 
image

**Comment by EndymionJkb** [comment]
> > I'm still getting those if I run at the package level though (e.g., standalone-utils) - even if I put the same line in the local package.json...
> 
> This works @EndymionJkb <img alt="image" width="895" src="https://user-

Could just change all the package level jsons like this then. This works for me, and would be clearer. Can you update all the packages? I run it at the package level more commonly than at root.

"lint:typescript": "NODE_NO_WARNINGS=1 eslint . ...

**Review by EndymionJkb — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
